name: WebSandboxMC
main: io.github.satoshinm.WebSandboxMC.bukkit.WebSandboxPlugin
version: ${version}
commands:
    websandbox:
        description: Controls the WebSandbox WebGL HTML5 web interface.
        usage: "Usage: /websandbox list|tp|kick|auth"
